/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * arrayProg.java
 *
 * Created on 8 Aug, 2010, 11:16:47 PM
 */

package arrayprog;

import java.awt.Color;
import java.util.Arrays;
import java.util.StringTokenizer;
import javax.swing.AbstractButton;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import javax.swing.text.StyledDocument;
/**
 *
 * @author abhiramj
 */
public class arrayProg extends javax.swing.JApplet {

    /** Initializes the applet arrayProg */
    @Override
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        drawPanel1 = new arrayprog.DrawPanel(program,program2D);
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton2.setVisible(false);
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextArea2.setVisible(false);
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton1.setVisible(false);
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton2.setVisible(false);
        jPanel7 = new javax.swing.JPanel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton2.setVisible(false);
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        jPanel3.setBackground(java.awt.Color.lightGray);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Arrays");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(382, 382, 382)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(479, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Code Output");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout drawPanel1Layout = new javax.swing.GroupLayout(drawPanel1);
        drawPanel1.setLayout(drawPanel1Layout);
        drawPanel1Layout.setHorizontalGroup(
            drawPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        drawPanel1Layout.setVerticalGroup(
            drawPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        jTextArea3.setColumns(20);
        jTextArea3.setEditable(false);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addGap(155, 155, 155))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addComponent(drawPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(drawPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Code Execution");

        jTextPane1.setEditable(false);
        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setText("Next");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton1))
        );

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Enter Array size");

        jToggleButton2.setText(isCodeRunning());
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(10);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Enter Values here in Comma seperated value format: Ex: 1,6,8");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTextArea2);

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Generate Random values");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Enter values");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jRadioButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jRadioButton2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(34, 34, 34)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jToggleButton2)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Expt1", jPanel2);

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel13.setText("X");

        jLabel14.setText("Row");

        jLabel15.setText("Column");

        jLabel16.setText("Enter Matrix size for A");

        jButton4.setText("Generate values for A");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("Ok");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setText(isCodeRunning());
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(39, 39, 39)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addContainerGap(38, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jToggleButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel16)
                .addGap(37, 37, 37)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jToggleButton3)
                .addGap(40, 40, 40)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jToggleButton4)
                .addGap(99, 99, 99))
        );

        jTabbedPane1.addTab("Expt2", jPanel7);

        jLabel5.setText("i    =");

        jLabel6.setText("j    =");

        jLabel7.setText("size  =");

        jLabel8.setText("key  =");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addContainerGap(342, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Variables", jPanel6);

        jToggleButton1.setText("Switch to 2D Arrays");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1)))
                .addContainerGap())
        );

        int count = jTabbedPane1.getTabCount();
        for (int m=0;m<count; m++){
            String label = jTabbedPane1.getTitleAt(m);
            if (label.equalsIgnoreCase("Expt2")){
                jTabbedPane1.setEnabledAt(m, false);
                this.validate();
            }

        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:




    }//GEN-LAST:event_jButton1MouseClicked

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        if (code_running==true){
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jTextArea2.setVisible(false);
        jTextArea2.setText("");
        }
                 switch (this.progSel){
            case 0:
                if (jRadioButton2.isSelected()==true){
                StringTokenizer strTok = new StringTokenizer(jTextArea2.getText(), ",");
        for (int i=0;i<size;i++){
            //this.A = new int[size];
        A[i] = Integer.parseInt(strTok.nextToken());
        }
                }
                if (jRadioButton1.isSelected()==true){
                for(int i=0;i<size;i++){
        A[i] = (int) (Math.random()*15);
        }
                }
System.out.println("In Start");
	        
	this.program = new coderunner(0,A,size);
drawPanel1.program=this.program;
drawPanel1.progSel=this.progSel;
	//this.program.setVars(p);
       switch (select) {

           case  0:
               jTextArea3.setText("Insertion sort is used to sort an set of n elements in ascending or descending order." +
                       " The elements are represented in a 1 Dimensional Array.Insertion sort in array of n elements works by assuming in" +
                       " ith iteration that i elements are sorted and i+1th element has to be inserted into this array.");
        this.initStyles = new String[progText.length];
	this.initStyles[0]="highlight";
	Arrays.fill(this.initStyles,1,initStyles.length,"regular");
        break;
//           case 1:
//               this.initStyles = new String[disp2.length];
//	this.initStyles[0]="highlight";
//	Arrays.fill(this.initStyles,1,initStyles.length,"regular");
//               break;
//           case 2:
//               this.initStyles = new String[disp2.length];
//	this.initStyles[0]="highlight";
//	Arrays.fill(this.initStyles,1,initStyles.length,"regular");
//               break;


        }
	//MyTopJPanel.this.initStyles=replaceStr(initStyles);

        break;
            case 1:
                
                drawPanel1.progSel=this.progSel;
                System.out.println("In Start");
                  jTextArea3.setText("Figure below shows how two Matices are multiplied. The array representation" +
                          " is with a 2D Array. The highlighted boxes show the current row/column/element selected of" +
                          " each Array");
                   this.program2D = new coderunner2(this.matA, this.matB, size1, size2, size3,0);
                   drawPanel1.program2D=this.program2D;
                  
                  
                    this.initStyles = new String[progText2.length];
	this.initStyles[0]="highlight";
	Arrays.fill(this.initStyles,1,initStyles.length,"regular");
        }
        this.code_running=true;
	this.lPanelRefresh();
	this.cPanelRefresh();
        this.rPanelRefresh();
        if (
                jToggleButton2.getText().equalsIgnoreCase("Reset")){
            jToggleButton2.setSelected(false);
        jToggleButton2.setText("Start");
        }

    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                switch (progSel){
            case 0:
                this.initStyles=replaceStr(initStyles,program);
                break;
            case 1:
                this.initStyles=replaceStr(initStyles,program2D);
        }

        if (evt.getActionCommand().equalsIgnoreCase("next")){
	System.out.println("In Next");
	try{

	this.rPanelRefresh();
	this.lPanelRefresh();
	this.cPanelRefresh();

	}

        catch (Exception n){
		code_running=false;
		System.out.println(n);
	}
        jToggleButton2.setText(isCodeRunning());

	}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String p = jFormattedTextField1.getText().replace(" ", "");



        size=Integer.parseInt(p);
        this.A = new int[size];
        jToggleButton2.setVisible(true);
        jTextArea2.setVisible(true);
        jRadioButton1.setVisible(true);
        jRadioButton2.setVisible(true);
        jRadioButton2.setSelected(true);
        //jTextArea2.setVisible(false);
        //jTextArea2.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextArea2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea2MouseClicked
        // TODO add your handling code here:
        if(tBoxInit==0){
        jTextArea2.setText("");
        tBoxInit=1;
        }
    }//GEN-LAST:event_jTextArea2MouseClicked

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jTextArea2.setVisible(true);
        jTextArea2.setEnabled(true);
        //this.A = null;
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
int count =jTabbedPane1.getTabCount();
System.out.println(count);
AbstractButton b = (AbstractButton) evt.getSource();
        switch (this.progSel){
            case 0:
this.progSel=1;
for (int m=0;m<count; m++){
String label = jTabbedPane1.getTitleAt(m);
if (label.equalsIgnoreCase("Expt2")){
jTabbedPane1.setEnabledAt(m, true);
jTabbedPane1.setSelectedIndex(m);
this.validate();
break;
}

}
for (int m=0;m<count; m++){
String label = jTabbedPane1.getTitleAt(m);
if (label.equalsIgnoreCase("Expt1")){
jTabbedPane1.setEnabledAt(m, false);
this.validate();
break;
}

}

System.out.println("In button");
b.setText("Switch to 1D Arrays");

break;


            case 1:
    this.progSel=0;
for (int m=0;m<count; m++){
String label = jTabbedPane1.getTitleAt(m);
System.out.println(label);
if (label.equalsIgnoreCase("Expt1")){
jTabbedPane1.setEnabledAt(m, true);
jTabbedPane1.setSelectedIndex(m);
this.validate();
break;
}


}
    for (int m=0;m<count; m++){
String label = jTabbedPane1.getTitleAt(m);
if (label.equalsIgnoreCase("Expt2")){
jTabbedPane1.setEnabledAt(m, false);
this.validate();
break;
}


}
b.setText("Switch to 2D Arrays");
break;
        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        if (input_stage==3){
            this.matB = new int[size2][size3];
            int i,j;
        for (i=0;i<size2;i++){
        for (j=0;j<size3;j++){
            
        this.matB[i][j]= (int)(Math.random()*15);
        System.out.println("Element wit pos i,j is" + i +" "+ j +" "+ this.matB[i][j]);
        }

        }

            //jFormattedTextField3.setEnabled(true);

        }
        if (input_stage==1){
                input_stage=2;
this.matA = new int[size1][size2];
        int i,j;
        for (i=0;i<size1;i++){
        for (j=0;j<size2;j++){
            
        matA[i][j] = (int)(Math.random()*15);
        System.out.println("Element wit pos i,j is" + i +" "+ j +" "+ this.matA[i][j]);
        }
        jToggleButton3.setSelected(false);
        jToggleButton3.setText("Ok");
        }
jLabel16.setText("Enter row/column size for B");
jFormattedTextField2.setText(jFormattedTextField3.getText());
jFormattedTextField2.setEnabled(false);
jFormattedTextField3.setEnabled(true);
jButton4.setEnabled(false);
jButton4.setText("Generate values for B");
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        if (input_stage==3){
        jFormattedTextField3.setEnabled(true);
        //jToggleButton3.setSelected(false);
        jToggleButton3.setText("Ok");
        }
        if (input_stage == 2)
        {
        
            this.size2=Integer.parseInt(jFormattedTextField2.getText());
       this.size3=Integer.parseInt(jFormattedTextField3.getText());
       jToggleButton3.setText("Clear");
       jButton4.setEnabled(true);
input_stage=3;
        }
        if (input_stage == 1)
        {
        jToggleButton3.setText("Ok");

        input_stage=2;
       // jFormattedTextField2.setEnabled(false);
        //jFormattedTextField3.setEnabled(true);
        }
        if (input_stage==0){
        this.size1=Integer.parseInt(jFormattedTextField2.getText());
       this.size2=Integer.parseInt(jFormattedTextField3.getText());
jFormattedTextField2.setEnabled(false);
jFormattedTextField3.setEnabled(false);
input_stage=1;
jToggleButton3.setText("Clear");
jButton4.setEnabled(true);
    }
        

    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
        jToggleButton2ActionPerformed(evt);
    }//GEN-LAST:event_jToggleButton4ActionPerformed
String switchProg(int progSel){
if (progSel==1)
{
    return "Switch to 1D Arrays";
}
else
    {
    return "Switch to 2D Arrays";
}
}int progSel=0;
int size;
int tBoxInit=0;
coderunner program;
coderunner2 program2D;
String[] initStyles;
int select=0;
public boolean code_running = false;
int matA[][];
int matB[][];
int matMult[][];
int A[];
int size1;
int size2;
int size3;
int input_stage=0;
        String [] progText = {"int main(){" +"\n",
        "int i,j,size,key;"+"\n",
        "for(i=1;i<size;i++)"+"\n",
        "   {"+"\n",
        "   key=A[i];"+"\n",
        "   j=i-1;"+"\n",
        "   while(j>=0 && A[j]>key)"+"\n",
        "      {"+"\n",
        "      A[j+1]=A[j];"+"\n",
        "      j--;"+"\n",
        "      }"+"\n",
        "   A[j+1]=key;"+"\n",
        "}"+"\n",
        "return 0;"+"\n",
        "}"
        };
         String [] progText2 = {"void main(){" +"\n",
        "int i,j,k;"+"\n",
        "int matA[i][j];"+"\n",
        "int matB[j][k];"+"\n",
        "matMult[i][k];"+"\n",
        "int p,q,r;"+"\n",
        "for (p=0;p<i;p++)"+"\n",
        "      {"+"\n",
        "      for(r=0;r<k;r++)"+"\n",
        "         {"+"\n",
        "         matMult[p][r]=0; "+"\n",
        "         for(q=0;q<j;q++)"+"\n",
        "            {"+"\n",
        "               matMult[p][r] += matA[p][q] * matB[q][r];"+"\n",
        "            }"+"\n",
         "        }"+"\n",
         "     }"+"\n",
         "}"
        };
        private void addStylestoDocument(StyledDocument doc) {
				// TODO Auto-generated method stub
				Style def = StyleContext.getDefaultStyleContext().getStyle(StyleContext.DEFAULT_STYLE);
				@SuppressWarnings("unused")
				Style regular =doc.addStyle("regular", def);
				StyleConstants.setFontFamily(regular, "SansSerif");
                                //StyleConstants.setLeftIndent(regular, 10f);
				//StyleConstants.setFirstLineIndent(regular,15.0f );

				Style highlight = doc.addStyle("highlight", def);
				StyleConstants.setForeground(highlight, Color.red);
                                StyleConstants.setBold(highlight, true);
                                //StyleConstants.setLeftIndent(highlight, 10f);

				Style indent = doc.addStyle("indent", null);
				StyleConstants.setFirstLineIndent(indent,15.0f );

			}
        void cPanelRefresh(){
//            if (program.currindex==12){
//            for (int i=0; i<program.size;i++)
//            {
//            String str = jTextPane2.getText();
//          jTextPane2.setText(str + program.A[i]+"," );
//        }
//            String str = jTextPane2.getText();
//            jTextPane2.setText(str + "\n" );
//            }

drawPanel1.repaint();

}
            private void lPanelRefresh(){
        switch (progSel){
            case 0:
try{
      this.jLabel5.setText("i   =");
            this.jLabel6.setText("j   =");
            this.jLabel7.setText("size   =");
            this.jLabel8.setText("key   =");
            this.jLabel8.setVisible(true);
            this.jLabel12.setVisible(true);
    this.jLabel9.setText(Integer.toString(program.i));
        this.jLabel10.setText(Integer.toString(program.j));
        this.jLabel11.setText(Integer.toString(program.size));
        this.jLabel12.setText(Integer.toString(program.key));
} catch (Exception e){}
break;
        case 1:
              this.jLabel5.setText("p   =");
            this.jLabel6.setText("q   =");
            this.jLabel7.setText("r   =");
            this.jLabel8.setVisible(false);
            this.jLabel12.setVisible(false);
//            this.jLabel8.setText("l   =");
//            this.jLabel4.setText("i   =");
//            this.jLabel6.setText("j   =");
//            this.jLabel10.setText("k   =");
//            this.jLabel12.setText("l   =");
//this.jLabel10.setVisible(true);
//        this.jLabel11.setVisible(true);
//        this.jLabel12.setVisible(true);
//        this.jLabel13.setVisible(true);
this.jLabel9.setText(Integer.toString(program2D.p));
this.jLabel10.setText(Integer.toString(program2D.q));
this.jLabel11.setText(Integer.toString(program2D.r));
//this.jLabel13.setText(Integer.toString(nested.l));
            break;
        }
        }


private void rPanelRefresh(){

		StyledDocument doc = jTextPane1.getStyledDocument();
//				StyledDocument blank = new DefaultStyledDocument();
				if (doc.getLength()!=0 ){
					try {
						doc.remove(0, doc.getLength());
					} catch (BadLocationException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}

				try{

					addStylestoDocument(doc);
                                        switch (progSel){
                                            case 0:


                                                // This code prints comments for simple loop
                                                jTextArea1.setText(program.comments.toString());

						if (code_running ==false){
							this.initStyles = new String [progText.length];
							System.out.println("Length is "+ progText.length);
						Arrays.fill(this.initStyles,"regular");
						}
					for(int i=0;i<this.progText.length;i++)
					{
						doc.insertString(doc.getLength(), this.progText[i], doc.getStyle(this.initStyles[i]));
					}
					break;
                                            case 1:
//                                                   jTextArea1.setText(program2D.comments.toString());

						if (code_running ==false){
							this.initStyles = new String [progText2.length];
							System.out.println("Length is "+ progText2.length);
						Arrays.fill(this.initStyles,"regular");
						}
					for(int i=0;i<this.progText2.length;i++)
					{
						doc.insertString(doc.getLength(), this.progText2[i], doc.getStyle(this.initStyles[i]));
					}
					break;

					default:
                                            if (code_running ==false){
					Arrays.fill(this.initStyles,"regular");
							}
						for(int i=0;i<this.progText.length;i++)
						{
							doc.insertString(doc.getLength(),this.progText[i], doc.getStyle(this.initStyles[i]));
						}
						break;
					}


				} catch (Exception e) {System.out.println(e);
				}
}

public String isCodeRunning(){
if (code_running==true){
return "Reset";

}
else {jToggleButton2.setSelected(false);
    return "Start";
}
}
    private String[] replaceStr (String [] initSt, Object programSel){
		for (int i =0; i<initSt.length;i++){
		String st = initSt[i];
		int index;
		if (st.equals("highlight"))
				{
			index = i;
			initSt[i]="regular";
			if (i>=initSt.length){
				break;
			}
                        switch(progSel){
                            case 0:
                               coderunner sp1 =(coderunner) programSel;
                                index=sp1.detnxtStmt(index,select);
                                break;
                            case 1:
                                coderunner2 sp2 = (coderunner2) programSel;
                                index=sp2.detnxtStmt(index, select);
                                break;
                        }
			System.out.println("Index is" + index);
			if (index==-1){
			this.code_running=false;
			System.out.println("done running on error or normal exit");
			//System.out.println(program.fact);
			}
			else{
			initSt[index]="highlight";
			break;
			}

				}
	}
	return initSt;
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private arrayprog.DrawPanel drawPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables

}
